import RPi.GPIO as GPIO
from time import sleep

GPIO.setmode(GPIO.BCM)
GPIO.setup(5,GPIO.OUT)
GPIO.output(5,False)
GPIO.setup(6,GPIO.OUT)
GPIO.output(6,False)
GPIO.setup(13,GPIO.OUT)
GPIO.output(13,False)
GPIO.setup(19,GPIO.OUT)
GPIO.output(19,False)
GPIO.setup(26,GPIO.OUT)
GPIO.output(26,False)
GPIO.setup(17,GPIO.OUT)	
GPIO.output(17,False)
GPIO.setup(18,GPIO.OUT)
GPIO.output(18,False)
GPIO.setup(22,GPIO.OUT)
GPIO.output(22,False)
GPIO.setup(23,GPIO.OUT)
GPIO.output(23,False)
GPIO.setup(24,GPIO.OUT)
GPIO.output(24,False)
GPIO.setup(27,GPIO.OUT)
GPIO.output(27,False)
GPIO.cleanup()
